In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("project_data.csv")
data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
4            4.0   1.229658   0.141004  0.045371  1.202613  0.191881   
5            7.0  -0.894286   0.286157 -0.113192 -0.271526  2.669599   
6            9.0  -0.338262   1.119593  1.044367 -0.222187  0.499361   
7           10.0   1.249999  -1.221637  0.383930 -1.234899 -1.485419   
8           11.0   1.069374   0.287722  0.828613  2.712520 -0.178398   
9           12.0  -2.791855  -0.327771  1.641750  1.767473 -0.136588   
10          12.0  -0.752417   0.345485  2.057323 -1.468643 -1.158394   
11          13.0  -0.436905   0.918966  0.924591 -0.727219  0.915679   
12          15.0   1.492936  -1.029346  0.454795 -1.438026 -1.555434   
13          16.0   0.694885  -1.361819  1.029221  0.834159 -1.191209   
14          18.0   1.166616   0.502120 -0.067300  2.261569  0.428804   
15          18.0   0.247491   0.277666  1.185471 -0.092603 -1.314394   
16          22.0  -1.946525  -0.044901 -0.405570 -1.013057  2.941968   
17          22.0  -2.074295  -0.121482  1.322021  0.410008  0.295198   
18          23.0   1.173285   0.353498  0.283905  1.133563 -0.172577   
19          23.0   1.322707  -0.174041  0.434555  0.576038 -0.836758   
20          23.0  -0.414289   0.905437  1.727453  1.473471  0.007443   
21          23.0   1.059387  -0.175319  1.266130  1.186110 -0.786002   
22          24.0   1.237429   0.061043  0.380526  0.761564 -0.359771   
23          25.0   1.114009   0.085546  0.493702  1.335760 -0.300189   
24          26.0  -0.529912   0.873892  1.347247  0.145457  0.414209   
25          26.0  -0.535388   0.865268  1.351076  0.147575  0.433680   
26          27.0  -1.452187   1.765124  0.611669  1.176825 -0.445980   
27          32.0   1.249055  -0.624727 -0.710589 -0.991600  1.429973   
28          32.0  -2.008872   2.198527  0.144242  1.159432 -0.815174   
29          33.0  -0.607877   1.031345  1.740450  1.232106  0.418592   
...          ...        ...        ...       ...       ...       ...   
199334  172758.0  -0.546378   1.433992 -0.313252  0.926044  0.522388   
199335  172759.0  -1.570301   1.880590 -0.559004 -1.003017 -0.326096   
199336  172759.0   1.894910  -0.427906 -2.184267  0.159979  0.587740   
199337  172760.0  -6.713826   2.369104 -3.534768 -0.368259 -1.721030   
199338  172761.0  -0.066136   0.996296 -0.918564 -0.923242  1.256522   
199339  172762.0   1.955547  -0.724606 -1.706511 -0.611145  1.710907   
199340  172762.0  -1.143909   1.780421 -0.454124 -0.814393  0.514689   
199341  172764.0  -0.764523   0.588379 -0.907599 -0.418847  0.901528   
199342  172766.0   1.975178  -0.616244 -2.628295 -0.406246  2.327804   
199343  172766.0  -1.139015  -0.155510  1.894478 -1.138957  1.451777   
199344  172767.0  -0.268061   2.540315 -1.400915  4.846661  0.639105   
199345  172768.0  -1.796092   1.929178 -2.828417 -1.689844  2.199572   
199346  172768.0  -0.669662   0.923769 -1.543167 -1.560729  2.833960   
199347  172768.0  -2.076175   2.142238 -2.522704 -1.888063  1.982785   
199348  172769.0  -1.029719  -1.110670 -0.636179 -0.840816  2.424360   
199349  172770.0   2.007418  -0.280235 -0.208113  0.335261 -0.715798   
199350  172770.0  -0.446951   1.302212 -0.168583  0.981577  0.578957   
199351  172771.0  -0.515513   0.971950 -1.014580 -0.677037  0.912430   
199352  172774.0  -0.863506   0.874701  0.420358 -0.530365  0.356561   
199353  172774.0  -0.724123   1.485216 -1.132218 -0.607190  0.709499   
199354  172775.0   1.971002  -0.699067 -1.697541 -0.617643  1.718797   
199355  172777.0  -1.266580  -0.400461  0.956221 -0.723919  1.531993   
199356  172778.0 -12.516732  10.187818 -8.476671 -2.510473 -4.586669   
199357  172780.0   1.884849  -0.143540 -0.999943  1.

### 원하는 feature 뽑아오기

In [3]:
def SelectFeature(data, feature_list):
    
    X = data[feature_list].values
    y = data['Class'].values
    
    return X,y;

### 테스트 케이스 나누기

In [4]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

#feature 전체
#feature_list = ['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15',
#               'V16','V17','V18','V19','V20','V21','V22','V23','V24','V25','V26','V27','V28'];

#좋은 feature 선별
feature_list = ['V11','V12','V14','V16','V17'];

train_X,train_y = SelectFeature(train_set,feature_list);
test_X , test_y = SelectFeature(test_set,feature_list);

print(train_X);
print(train_y);


[[ 0.81099033 -0.1571694   0.27748237  0.72035363 -1.02928337]
 [-0.62248837 -0.42627382  0.0181458  -0.1545095  -0.07384783]
 [-0.89717365 -0.60006335 -0.4411297  -0.7057944   0.5662706 ]
 ...
 [-0.93265781 -0.7207458  -1.40515701  1.05989662  0.20521758]
 [-0.80920114 -0.79244229 -0.30558514  0.12329527  0.81762068]
 [ 1.08859349 -0.22640575  0.67057696  0.61510765  0.1784389 ]]
[0 0 0 ... 0 0 0]


### f1 Measure

In [5]:
from sklearn.metrics import f1_score

def CalScore(true,predict):

    f1Score = f1_score(true, predict, average='macro')
    print(f1Score)
    f1Score = f1_score(true, predict, average='micro')
    print(f1Score)
    f1Score = f1_score(true, predict, average='weighted')
    print(f1Score)
    f1Score = f1_score(true, predict, average=None)
    print(f1Score)

### Triforce

In [90]:
def Triforce(predict1,predict2,predict3):
    
    tri = (predict1 + predict2 + predict3)/3;
    print(np.sum(tri))
    tri = np.around(tri);
    print(np.sum(tri))
    
    return tri;
    

### Logistic Regression

In [96]:
from sklearn.linear_model import LogisticRegression

logit = LogisticRegression(C = 10000)
logit.fit(train_X, train_y)

#predict = logit.predict(train_X)
#CalScore(train_y,predict)

predict1 = logit.predict(test_X)
CalScore(test_y,predict1)

d:\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8223043396175964
0.9988964963759938
0.99877210128708
[0.99944739 0.64516129]


### SVM

In [7]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf')
svm.fit(train_X, train_y)

#predict = svm.predict(train_X)
#CalScore(train_y,predict)

predict2 = svm.predict(test_X)
CalScore(test_y,predict2)


d:\python\python37\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9133893858155369
0.9994231685601785
0.9993820351461841
[0.9997111  0.82706767]


### Decision Tree Classifier

In [66]:
from sklearn import tree

decisionTree = tree.DecisionTreeClassifier()
decisionTree.fit(train_X, train_y)


predict = decisionTree.predict(train_X)
CalScore(train_y,predict)

predict = decisionTree.predict(test_X)
CalScore(test_y,predict)


1.0
1.0
1.0
[1. 1.]
0.8681697774098285
0.9989968148872671
0.9989968148872671
[0.99949745 0.73684211]


### Random Forest

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

rfc = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
rfc.fit(train_X, train_y)

#predict = rfc.predict(train_X)
#CalScore(train_y,predict)

predict3 = rfc.predict(test_X)
CalScore(test_y,predict3)

0.8434988005224948
0.9989968148872671
0.998902917482694
[0.9994976 0.6875   ]


In [68]:
triforce = Triforce(predict1,predict2,predict3)
print(triforce)

CalScore(test_y,triforce)

50.333333333333336
52.0
[0. 0. 0. ... 0. 0. 0.]
0.8434988005224948
0.9989968148872671
0.998902917482694
[0.9994976 0.6875   ]


### Gradient Boosting Classifier

In [69]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier()
gbc.fit(train_X, train_y)

predict = gbc.predict(test_X)
CalScore(test_y,predict)



0.7031191431399509
0.9983196649361723
0.9980301070802856
[0.99915864 0.40707965]


In [74]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier()
xgb_model.fit(train_X, train_y)

predict = xgb_model.predict(test_X)
CalScore(test_y,predict)


0.8969809712048986
0.9992726907932686
0.9992443708266051
[0.9996357  0.79432624]


### MLP Classifier

In [79]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)  
mlp.fit(train_X, train_y)  

predict = mlp.predict(test_X)
CalScore(test_y,predict)


0.9131700085431429
0.9993479296767236
0.9993435907334851
[0.99967335 0.82666667]


### k-NN

In [82]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(train_X, train_y)

predict = knn.predict(test_X)
CalScore(test_y,predict)


0.9099149210785755
0.9993730093045419
0.9993437407902483
[0.99968596 0.82014388]


### svm 파라미터 튜닝

In [98]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.001,0.01,0.1, 1, 10, 100,1000], 'gamma': [10, 1, 0.1, 0.01, 0.001, 0.00001]}


clf = GridSearchCV(SVC(), param_grid, verbose=1)
clf.fit(train_X, train_y)

print("Best Parameters:\n", clf.best_params_)
print("Best Estimators:\n", clf.best_estimator_)

d:\python\python37\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 42 candidates, totalling 126 fits


[Parallel(n_jobs=1)]: Done 126 out of 126 | elapsed: 93.9min finished


Best Parameters:
 {'C': 10, 'gamma': 0.1}
Best Estimators:
 SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [6]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf',C=10,gamma=0.1)
svm.fit(train_X, train_y)

#predict = svm.predict(train_X)
#CalScore(train_y,predict)

predict2 = svm.predict(test_X)
CalScore(test_y,predict2)

0.8998241338592567
0.9992977704210869
0.9992677277955933
[0.99964827 0.8       ]


In [7]:
valueArray = [];

for i in range(28):
    valueArray.append(data['V'+str(i+1)])

In [8]:
col = np.where(result==0,'b','r')

for i in range(len(valueArray)):
    for j in range(len(valueArray)):
        print(i+1,j+1)
        #plt.scatter(valueArray[i],valueArray[j],c=col,s=10)
        #plt.savefig("cov"+str(i)+str(j)+".png")
        #plt.clf()
        

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
2 16
2 17
2 18
2 19
2 20
2 21
2 22
2 23
2 24
2 25
2 26
2 27
2 28
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
3 10
3 11
3 12
3 13
3 14
3 15
3 16
3 17
3 18
3 19
3 20
3 21
3 22
3 23
3 24
3 25
3 26
3 27
3 28
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
4 10
4 11
4 12
4 13
4 14
4 15
4 16
4 17
4 18
4 19
4 20
4 21
4 22
4 23
4 24
4 25
4 26
4 27
4 28
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
5 10
5 11
5 12
5 13
5 14
5 15
5 16
5 17
5 18
5 19
5 20
5 21
5 22
5 23
5 24
5 25
5 26
5 27
5 28
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
6 10
6 11
6 12
6 13
6 14
6 15
6 16
6 17
6 18
6 19
6 20
6 21
6 22
6 23
6 24
6 25
6 26
6 27
6 28
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
7 10
7 11
7 12
7 13
7 14
7 15
7 16
7 17
7 18
7 19
7 20
7 21
7 22
7 23
7 24
7 25
7 26
7 27
7 28
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
8 10
8 11
8 12
8 13
8 14
8 15
8 16
8 17
8 18
8 

In [9]:

for i in range(len(valueArray)):
    print(i)
    print(np.mean(valueArray[i]))
    print(np.var(valueArray[i]))
    print(np.std(valueArray[i]))
    #plt.scatter(time,valueArray[i],c=col,s=10)
    #plt.savefig("value"+str(i)+".png")
    #plt.clf()

0
-0.003370153263307601
3.849591828427786
1.9620376725302158
1
0.0009989272770197716
2.757126388159257
1.6604596918200867
2
0.0004080125078719491
2.3041277610233655
1.5179353612797106
3
0.0031398879531128274
2.010639537183285
1.417970217311804
4
0.0006059713480719164
1.9214211708025348
1.3861533720344712
5
-0.00016432192844623237
1.7835095724498509
1.335481026615448
6
0.001902354583129389
1.5576292337595443
1.2480501727733322
7
-0.0011247242026774546
1.4312386917702324
1.1963438852479802
8
0.0007226963880086407
1.2094352889259228
1.0997432831920015
9
-0.001475384838393684
1.1971786561847864
1.0941565958238273
10
0.0013898046105778248
1.0444270844230639
1.0219721544264617
11
-0.0016884974514489828
1.0072842222987084
1.0036355027093793
12
-0.0031960345874183127
0.9910193103362939
0.9954995280442346
13
-0.0009140242950301451
0.9249473483552314
0.9617418304073247
14
-0.00028474145381528735
0.8404485267287229
0.9167597977271489
15
0.000534280165461583
0.7698000485081136
0.8773824984054067
1